version: '3.9'
services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "81:81"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app_networks

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - app_networks
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_networks:
    driver: bridge

volumes:
  redis_data:
