version: '3.9'
services:
  app:
    build: .
    container_name: my-node-app
    command: >
      sh -c "npx prisma generate && npm start"
    ports:
      - "81:81" # Correct format for a list
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_networks

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379" # Correct format for a list
    networks:
      - app_networks
    volumes:
      - redis_data:/data # Correct format for a list

networks:
  app_networks:
    driver: bridge

volumes:
  redis_data: