version: '3.9'
services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      my-redis-container:
        condition: service_healthy
    networks:
      - app_networks

  my-redis-container:
    image: redis:7.4.0
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app_networks
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_networks:
    driver: bridge

volumes:
  redis_data:
